### ISSUE TITLE
KUDOS. Couple of ideas, and a question

### ISSUE THREAD

**Issue by depesz** [AmirRezaM75/skullking#13]
Hi,
first of all - WOW! Amazing stuff. My family is currently distributed around the world, and we love SkullKing. Your site and software is absolutely amazing.

Would love if you could add couple of things:
1. when starting new trick, show summary how many tricks, in total, players bidded to take, vs. how many there are.
2. highlight currently winning card/player
3. add a graph with score?

What would it take to add support for tigress/scary mary? I read that it's complicated, but perhaps doable? Could I "bribe" you somehow?

Best regards,

depesz

**Comment by depesz** [comment]
One more thing - can you link to some donation place that has english interface? I'd like to donate, but I can't read this language (farsi?)

**Comment by AmirRezaM75** [comment]
Thank you @depesz so much for your kind words! I'm thrilled to hear that you and your family are enjoying SkullKing. It's always a joy for us to know that our software are bringing people together, even across distances.

**Comment by AmirRezaM75** [comment]
1)
Right now, we show how many bids players want to take in each round (green box). We also show how many bids they actually won (pink box). And just to clarify, the number of tricks in each round is equal to the round number (red circle). So, if it's round 8, there will be 8 tricks in total.

![Screenshot from 2024-03-10 08-20-34](https://github.com/AmirRezaM75/skullking/assets/20792176/61ef0678-5a09-4efd-8303-70db9b4843b5)

**Comment by AmirRezaM75** [comment]
2. It's a cool feature. Put it on my TODO list.

**Comment by AmirRezaM75** [comment]
3. It's also a good feature.I need to think about the design, because it would be good to also show bonus points to make it clear for everyone.

**Comment by AmirRezaM75** [comment]
4. Tigress adds lot's of work. First I need to find a design for the card. then we need to ask user to choose between being a pirate or escape when picking this card, but the worst part is backend side :)

**Comment by AmirRezaM75** [comment]
What is scary mary?

**Comment by AmirRezaM75** [comment]
5. Current donation page only supports Iranian Rial. I'll try to add paypal in the future. Thanks for your intention.

**Comment by AmirRezaM75** [comment]
1) Ok, I got it. You want to see sum of bids. for example if player A bids **0**, player B bids **4**, player C bids **2**. Total bids is 6.
5) Due to sanction is not really easy to send money to my country. You can support me by hitting "start" button.
![Screenshot from 2024-03-13 06-17-07](https://github.com/AmirRezaM75/skullking/assets/20792176/5611db97-6e11-45fc-868f-576ee9763adb)

6) will think about 'pausing the game'.

Don't hesitate if you had any other idea.

**Comment by AmirRezaM75** [comment]
@depesz 
I hope you are doing well.
Following changes are live. Tell me your feedback.

- [x] when starting new trick, show summary how many tricks, in total, players bidded to take, vs. how many there are.
- [x] Highlight currently winning card/player
- [x] Add a graph with score
- [x] New donation gateway (crypto)

A new graph displaying the scores has been added. You can view this graph by clicking on the icon located at the bottom left side of the sidebar.
![Screenshot from 2024-07-29 19-45-59](https://github.com/user-attachments/assets/89058ae3-249a-48ed-9740-526501f082ab)

The total bid is now displayed at the top of the sidebar.

![Screenshot from 2024-07-29 19-51-24](https://github.com/user-attachments/assets/15ef0e87-4862-47f8-aed3-56023ad68936)

The winning card is indicated by adding a star before the username.
![Screenshot from 2024-07-29 19-51-41](https://github.com/user-attachments/assets/ca7ba38a-f1bb-457d-a233-cfaaabb764b1)

For Tigress, I spoke with the game's publisher. We don't have full authority to replicate every detail of the game due to licensing restrictions. (Probably need to change the name in the future)

**Comment by depesz** [comment]
This is AWESOME. Thanks a lot.

**Comment by depesz** [comment]
Hi. One more thing. I tried to sent you donation in crypto, but got message "Donation Was Partially Received
Your donation is complete, but the amount sent was not sufficient to cover the estimated transaction price. Please contact your recipient for additional payment details.".

Please check if you got anything. There is additional bit: Payment ID 4639899662

**Comment by AmirRezaM75** [comment]
Thanks @depesz , Everything is fine and I received the money :pray:
